wget https://github.com/xmrig/xmrig/releases/download/v6.12.2/xmrig-6.12.2-linux-x64.tar.gz

tar -zxvf xmrig-6.12.2-linux-x64.tar.gz

cd xmrig-6.12.2

./xmrig -o rx.unmineable.com:3333 -a rx -k -t 3 -u DOGE:DBSUU34MZPXJVeDjVKZ7wGsFB8DyXfVZmP.miner3#oybp-oa60
